### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ktstowell**
@dylantack Here's another one! I am working on this actively again so if you could add me as a collaborator that would be rad. Then I wouldn't have to bug you.

### CODE REVIEW

**Comment by ktstowell** [comment]
@dylantack So github sent me an email saying you merged this but the page it self still show it as unmerged, weird.

**Comment by AceMaridiam** [comment]
I'm not sure as to why I'm attached to these emails.  You may want to remove me.

Paul R Anderson
Junior Web Developer / 
Video Producer

**Comment by ktstowell** [comment]
@AceMaridiam Because you belong to Metal Toad's github organization you are by default added to the notification list. Just click the 'unwatch' button up top and it should remove you.

**Comment by twardnw** [comment]
Odd, we have another user who reported getting notices from Valence too, neither are in MTM's org, not sure why the notifications are being sent to them.

**Comment by marcus-n3rd** [comment]
Is valence a public repo?

## 

Marcus Bernal https://www.linkedin.com/pub/marcus-bernal/99/78a/757  |
Developer
Metal Toad http://www.metaltoad.com/  |  _Technology Consultants
Modernizing Business_  |  (503) 336-1658  |  Portland, OR

http://www.oregonbusiness.com/articles/170-march-2015/14673-the-100-best-companies-to-work-for-in-oregon

**Comment by dylantack** [comment]
Yes, it's an open-source project under the MIT license.

**Pull request merged**
